############################################################
#
# Purpose: Makefile for Beat and Tempo Tracking Demos
# Author:  Michael Krzyzaniak
#
############################################################

TARGET      := demo
CXX         := gcc
CXXFLAGS    += -Wall -O
OBJECTS     := $(wildcard $*.o)
INSTALL_DIR := ./

$(TARGET): $(OBJECTS)
	$(CXX) $(CFLAGS) $(LFLAGS) $(OBJECTS) -o $(TARGET)
	rm -f $(OBJECTS)

clean: 
	rm -f $(OBJECTS) $(TARGET)